import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form action="" onsubmit="searchPokemon(event)">
            <input type="text" name="pokemon" autocomplete="off"/>
        </form>
        <div data-poke-card class="poke-card">
            <div data-poke-name>Pokedex</div>
            <div data-poke-img-container className="img-container">
                <img data-poke-img className="poke-img" src="/Poke-Gif.gif"/>
            </div>
            <div data-poke-id></div>
            <div data-poke-types className="poke-types"></div>
            <div data-poke-stats className="poke-stats"></div>
            <div data-poke-moves className="poke-moves"></div>
        </div>
    </div>
  )
}
